### ISSUE TITLE
mxnet-model-export zipping everything

### ISSUE THREAD

**Issue by pracheer** [awslabs/mxnet-model-server#267] opened 2018-01-11 21:00 UTC
Not sure if this is an issue but could be considered one.

I had a directory with .onnx file and signature.json file along with few other random files. mxnet-model-export zipped those random files too.

**Comment by lupesko** [comment] 2018-01-12 07:28
This is by design: -export packs up *everything* in the target dir. Reason is that users may want to use auxiliary files in their custom code.
Closing.

**Closed by lupesko** 2018-01-12 07:28 UTC
