### ISSUE TITLE
Floating point exception(core dumped) python /mxnet_model_server/setup_mms.py $models

### ISSUE THREAD

**Issue by uniquezhengjie** [awslabs/mxnet-model-server#480] opened 2018-08-08 05:41 UTC
when i run command like "mxnet-model-server start --mms-config /mxnet_model_server/mms_app_cpu.conf" or mxnet-model-export my own model, reture an err:
* Restarting nginx nginx                                                                                                                                                                            [ OK ] 
/mxnet_model_server/mxnet-model-server: line 22:    72 Floating point exception(core dumped) python /mxnet_model_server/setup_mms.py $models
INFO: Ending the program

i run same docker images in two computers get different result,ones  is good job,but anothor get error like this,someone can help me?

**Comment by vdantu** [comment] 2018-08-08 06:07
@uniquezhengjie 
Are you getting this when running the mms_app_cpu.conf in the container, without any changes? Or is this happening with your model? 

Also, are you getting this error with mxnet-model-export as well?

**Comment by uniquezhengjie** [comment] 2018-08-08 06:59
@vdantu yes.when i run mms_app_cpu.conf without any changes, if i mxnet-model-export my model and mxnet-model-server start (get model from by anothor computer) ,get that err

**Comment by uniquezhengjie** [comment] 2018-08-08 07:04
root@831152d0753e:/deploy# cat /mxnet_model_server/mms_app_cpu.conf
[MMS Arguments]
--models
squeezenet=https://s3.amazonaws.com/model-server/models/squeezenet_v1.1/squeezenet_v1.1.model

--service
optional

--gen-api
optional

--log-file
optional

--log-rotation-time
optional

--log-level
optional

--metrics-write-to
optional

[Gunicorn Arguments]

--bind
unix:/tmp/mms_app.sock

###number of workers is set to number of vCPUs by default##
--workers
optional

--worker-class
gevent

--limit-request-line
0

[Nginx Configurations]
server {
    listen       8080;

    location / {
        proxy_pass http://unix:/tmp/mms_app.sock;
    }
}

[MXNet Environment Variables]
OMP_NUM_THREADS=1
root@831152d0753e:/deploy# mxnet-model-server start --mms-config /mxnet_model_server/mms_app_cpu.conf
INFO: Reading file /mxnet_model_server/mms_app_cpu.conf
 * Restarting nginx nginx                                                                                                                                                                            [ OK ] 
/mxnet_model_server/mxnet-model-server: line 22:   382 Floating point exception(core dumped) python /mxnet_model_server/setup_mms.py $models
INFO: Ending the program
root@831152d0753e:/deploy# mxnet-model-server start --mms-config /mxnet_model_server/mms_app_cpu.conf
INFO: Reading file /mxnet_model_server/mms_app_cpu.conf
 * Restarting nginx nginx                                                                                                                                                                            [ OK ] 
/mxnet_model_server/mxnet-model-server: line 22:   433 Floating point exception(core dumped) python /mxnet_model_server/setup_mms.py $models
INFO: Ending the program
root@831152d0753e:/deploy# mxnet-model-server start --mms-config /mxnet_model_server/mms_app_cpu.conf
INFO: Reading file /mxnet_model_server/mms_app_cpu.conf
 * Restarting nginx nginx                                                                                                                                                                            [ OK ] 
/mxnet_model_server/mxnet-model-server: line 22:   484 Floating point exception(core dumped) python /mxnet_model_server/setup_mms.py $models
INFO: Ending the program

**Comment by vdantu** [comment] 2018-08-08 22:18
I think the issue is with the "import mms" in the setup_mms.py. That seems to be failing. Python inside the container isn't able to see the installed "mms" packge. We will look into this and get back.

**Comment by uniquezhengjie** [comment] 2018-08-09 01:37
You're right，I'm looking forward to your reply.

root@acdc81dec2a2:/# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mms
Floating point exception (core dumped)

**Comment by uniquezhengjie** [comment] 2018-08-10 01:37
i found that this err is related to mxnet-mkl ,my cpu is Intel(R) Xeon(R) CPU E5-26xx v4

**Comment by vdantu** [comment] 2018-08-11 09:47
@uniquezhengjie : Could you share how you found this issue? Also, which version of mxnet-mkl was causing the issue? Could you share "pip freeze" of your container environment.

**Comment by uniquezhengjie** [comment] 2018-08-11 10:51
@vdantu i create a issue ,https://github.com/apache/incubator-mxnet/issues/12105
ubuntu@master:~$ pip freeze
beautifulsoup4==4.4.1
blinker==1.3
boto3==1.7.71
certifi==2018.4.16
chardet==2.3.0
Cheetah==2.4.4
click==6.7
cloud-init==0.7.9
configobj==5.0.6
cryptography==1.2.3
enum34==1.1.2
fasteners==0.14.1
Flask-Cors==3.0.6
fuzzyfinder==2.1.0
graphviz==0.8.4
html5lib==0.999
httpie==0.9.2
httplib2==0.11.3
idna==2.0
importlib2==3.5.0.2
ipaddress==1.0.16
Jinja2==2.8
jsonpatch==1.10
jsonpointer==1.9
jsonschema==3.0.0a1
kube-shell==0.0.23
kubernetes==2.0.0
lxml==3.5.0
M2Crypto==0.22.6rc4
Markdown==2.6.6
MarkupSafe==0.23
mxnet-mkl==1.0.0
mxnet-model-server==0.4
ndg-httpsclient==0.4.0
numpy==1.15.0
oauth2client==4.1.2
oauthlib==1.0.3
onnx==1.1.1
prettytable==0.7.2
prompt-toolkit==1.0.15
psutil==5.4.6
pyasn1==0.1.9
pyasn1-modules==0.2.2
Pygments==2.1
PyJWT==1.3.0
pyOpenSSL==0.15.1
python-dateutil==2.7.3
PyYAML==3.11
requests==2.9.1
rsa==3.4.2
shadowsocks==2.1.0
six==1.10.0
urllib3==1.13.1
wcwidth==0.1.7
websocket-client==0.48.0

**Comment by vdantu** [comment] 2018-08-12 22:09
Just to narrow this down. Could you uninstall mxnet-mkl "1.2.1.post1" and install just "1.2.1" ? 
```
$ pip uninstall -y mxnet-mkl
$ pip install mxnet-mkl==1.2.1
```
I wanted to see if that solves this issue.

**Comment by vdantu** [comment] 2018-08-13 01:53
@uniquezhengjie : Thanks for trying this :) . I will look into this further.

**Comment by ThomasDelteil** [comment] 2018-08-15 02:04
encountered the same issue on Fargate, suggest reverting the default mxnet install to `pip install mxnet`

**Comment by vdantu** [comment] 2018-10-23 00:03
@uniquezhengjie and @ThomasDelteil :  I tried with latest mxnet-mkl (1.3.0) with python 3.5 and 2.7. I don't see this issue. I will close this issue. Please reopen it if it is still seen.

**Closed by vdantu** 2018-10-23 00:03 UTC
Labels: bug
