### ISSUE TITLE
Re running MMS says port is used but doesnt say which one is being used.

### ISSUE THREAD

**Issue by gautamkmr** [awslabs/mxnet-model-server#256] opened 2018-01-11 20:28 UTC
So I had MMS running and then I pressed CTRL-C and re-run the command it ended up with following stack trace 
/python3.6/site-packages/mms/mxnet_model_server.py:start_model_serving:110] Service health endpoint: 127.0.0.1:8080/ping
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/python3/bin/mxnet-model-server", line 11, in <module>
    sys.exit(start_serving())
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/mms/mxnet_model_server.py", line 206, in start_serving
    mms.start_model_serving()
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/mms/mxnet_model_server.py", line 112, in start_model_serving
    self.serving_frontend.start_handler(self.host, self.port)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/mms/serving_frontend.py", line 60, in start_handler
    self.handler.start_handler(host, port)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/mms/request_handler/flask_handler.py", line 48, in start_handler
    self.app.run(host=host, port=port)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 666, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Its good if the error message include which port is being used.

**Comment by jesterhazy** [comment] 2018-01-13 01:28
I can't reproduce this error on ubuntu 16.04 or osx. is it possible you hit ctrl-z instead of ctrl-c and background an instance of the server? or could you provide more details about your environment?

**Comment by frankfliu** [comment] 2018-10-23 21:42
Fixed in PR: https://github.com/awslabs/mxnet-model-server/pull/633

**Closed by frankfliu** 2018-10-23 21:42 UTC
Labels: logging, triaged
