### ISSUE TITLE
Fix "import imp" warning message for the usage command

### ISSUE THREAD

**Issue by bhavinthaker** [awslabs/mxnet-model-server#271] opened 2018-01-11 21:20 UTC
Instead of using "import imp", I suggest to use "import importlib" based on the error message below:

$ mxnet-model-export
/Users/thakerb/anaconda3/envs/mms_feb_2018_1/lib/python3.6/site-packages/mms/export_model.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
usage: mxnet-model-export [-h] --model-name MODEL_NAME --model-path MODEL_PATH
                          [--service-file-path SERVICE_FILE_PATH]
mxnet-model-export: error: the following arguments are required: --model-name, --model-path

**Comment by jesterhazy** [comment] 2018-01-12 00:35
duplicate of #254

**Closed by jesterhazy** 2018-01-12 00:35 UTC
