### ISSUE TITLE
onnx model serving of torchvision onnx model errors: Target shape size is different to source.

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#306] opened 2018-01-24 07:54 UTC
I tried several different models from Pytorch's torchvision and was met with a similar error. In this case I'm on my Mac and using python 3.6.
Depending on the model I try, the shape error is different. 

I'm trying to document a complete process from PyTorch model saving/exporting to ONNX to MMS converting/exporting to MMS serving/inference, but have yet to get it to work...

The onnx models are created by following [PyTorch's export docs](http://pytorch.org/docs/master/onnx.html). Only some will export according to these docs (for example, squeezenet and inception v3 both fail, but alexnet and vgg16 will export to a protobuf file). Then they can be packaged up into a model file with MMS, but they fail upon serving with MMS.

This step works:
```
from torch.autograd import Variable
import torch.onnx
import torchvision

dummy_input = Variable(torch.randn(10, 3, 224, 224))
model = torchvision.models.vgg16(pretrained=True)
torch.onnx.export(model, dummy_input, "vgg16.onnx", verbose=True)
```
Followed by the MMS export works, assuming you get the data_name right:
```
mxnet3.6) 8c8590217d260a:vgg16-pytorch markhama$ cat signature.json 
{
  "inputs": [
    {
      "data_name": "input_0",
      "data_shape": [0, 3, 224, 224]
    }
  ],
  "input_type": "image/jpeg",
  "outputs": [
    {
      "data_name": "softmax",
      "data_shape": [0, 1000]
    }
  ],
  "output_type": "application/json"
}
```
The export works, but with warnings:
```
(mxnet3.6) 8c8590217d260a:vgg16-pytorch markhama$ mxnet-model-export --model-name vgg16 --model-path .
/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.2-py3.6.egg/mms/export_model.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/onnx_mxnet/common.py:97: UserWarning: Attribute axis is disabled in sym.broadcast_add
  warnings.warn("Attribute {} is disabled in sym.{}".format(k, op_name))

```
Then the serving step fails.
```
(mxnet3.6) 8c8590217d260a:vgg16-pytorch markhama$ mxnet-model-server --models vgg16=vgg16.model --port 8089
/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.2-py3.6.egg/mms/service_manager.py:14: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[INFO 2018-01-23 23:42:57,178 PID:39158 /Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.2-py3.6.egg/mms/mxnet_model_server.py:__init__:94] Initialized model serving.
[ERROR 2018-01-23 23:42:58,721 PID:39158 /Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.2-py3.6.egg/mms/mxnet_model_server.py:_arg_process:185] Failed to process arguments: simple_bind error. Arguments:
input_0: (1, 3, 224, 224)
Error in operator reshape0: [23:42:58] src/operator/tensor/./matrix_op-inl.h:157: Check failed: oshape.Size() == dshape.Size() (25080 vs. 25088) Target shape size is different to source. Target: [10,2508]
Source: [1,512,7,7]

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010ec0fadf dmlc::StackTrace() + 303
[bt] (1) 1   libmxnet.so                         0x000000010ec0f87f dmlc::LogMessageFatal::~LogMessageFatal() + 47
[bt] (2) 2   libmxnet.so                         0x000000010fa6da28 mxnet::op::ReshapeShape(nnvm::NodeAttrs const&, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >*, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >*) + 7464
[bt] (3) 3   libmxnet.so                         0x000000010fbbd7ba nnvm::Graph mxnet::exec::InferAttr<nnvm::TShape, std::__1::function<bool (nnvm::NodeAttrs const&, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >*, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >*)>, mxnet::exec::InferShape(nnvm::Graph&&, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0, std::nullptr_t>(nnvm::Graph&&, nnvm::TShape, char const*, char const*, char const*, char const*, char const*, mxnet::exec::InferShape(nnvm::Graph&&, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0, std::nullptr_t, bool, char const*, mxnet::DispatchMode)::'lambda'(unsigned int, bool)::operator()(unsigned int, bool) const + 1978
[bt] (4) 4   libmxnet.so                         0x000000010fbb612e mxnet::exec::InferShape(nnvm::Graph&&, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 4542
[bt] (5) 5   libmxnet.so                         0x000000010fbabf56 mxnet::exec::GraphExecutor::Init(nnvm::Symbol, mxnet::Context const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::Context, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, mxnet::Context> > > const&, std::__1::vector<mxnet::Context, std::__1::allocator<mxnet::Context> > const&, std::__1::vector<mxnet::Context, std::__1::allocator<mxnet::Context> > const&, std::__1::vector<mxnet::Context, std::__1::allocator<mxnet::Context> > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, nnvm::TShape, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, nnvm::TShape> > > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, int> > > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, int> > > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> >*, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> >*, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> >*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArray, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, mxnet::NDArray> > >*, mxnet::Executor*, std::__1::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::__1::allocator<std::__1::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&) + 1030
[bt] (6) 6   libmxnet.so                         0x000000010fbae4f6 mxnet::Executor::SimpleBind(nnvm::Symbol, mxnet::Context const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::Context, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, mxnet::Context> > > const&, std::__1::vector<mxnet::Context, std::__1::allocator<mxnet::Context> > const&, std::__1::vector<mxnet::Context, std::__1::allocator<mxnet::Context> > const&, std::__1::vector<mxnet::Context, std::__1::allocator<mxnet::Context> > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, nnvm::TShape, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, nnvm::TShape> > > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, int> > > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, int> > > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> >*, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> >*, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> >*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArray, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, mxnet::NDArray> > >*, mxnet::Executor*) + 230
[bt] (7) 7   libmxnet.so                         0x000000010fb4e766 MXExecutorSimpleBind + 8038
[bt] (8) 8   _ctypes.cpython-36m-darwin.so       0x000000010dd5642f ffi_call_unix64 + 79
[bt] (9) 9   ???                                 0x00007fff52eddec0 0x0 + 140734584708800


(mxnet3.6) 8c8590217d260a:vgg16-pytorch markhama$ 
```

**Comment by jesterhazy** [comment] 2018-01-24 17:58
is your install of mms up to date? this error should be occuring in current version.

export_model.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by aaronmarkham** [comment] 2018-01-24 19:00
Updated and still getting these errors (minus the imp one).

**Comment by jesterhazy** [comment] 2018-01-24 19:43
export step wfm without warnings or errors:
$ mxnet-model-export --model-name onnx-vgg --model-path .

serving step does fail with bind/shape errors, but not the one you are seeing:

```
Failed to process arguments: simple_bind error. Arguments:
input_0: (1, 3, 224, 224)
Error in operator pad0: [11:36:00] src/operator/./pad-inl.h:211: Input shape vs padding spec mismatch.

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x0000000103e65598 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x0000000105090813 _ZNK5mxnet2op7PadProp10InferShapeEPNSt3__16vectorIN4nnvm6TShapeENS2_9allocatorIS5_EEEES9_S9_ + 1507
[bt] (2) 2   libmxnet.so                         0x0000000104f31bee _ZN5mxnet2op16OpPropInferShapeERKN4nnvm9NodeAttrsEPNSt3__16vectorINS1_6TShapeENS5_9allocatorIS7_EEEESB_ + 878
[bt] (3) 3   libmxnet.so                         0x0000000104dd4cca _ZZN5mxnet4exec9InferAttrIN4nnvm6TShapeENSt3__18functionIFbRKNS2_9NodeAttrsEPNS4_6vectorIS3_NS4_9allocatorIS3_EEEESD_EEEZNS0_10InferShapeEONS2_5GraphEOSC_RKNS4_12basic_stringIcNS4_11char_traitsIcEENSA_IcEEEEE3$_0DnEESG_SH_T_PKcST_ST_ST_ST_T1_T2_bST_NS_12DispatchModeEENKUljbE_clEjb + 1978
[bt] (4) 4   libmxnet.so                         0x0000000104dcd60e _ZN5mxnet4exec10InferShapeEON4nnvm5GraphEONSt3__16vectorINS1_6TShapeENS4_9allocatorIS6_EEEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS7_IcEEEE + 4542
[bt] (5) 5   libmxnet.so                         0x0000000104dc3066 _ZN5mxnet4exec13GraphExecutor4InitEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS7_12basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEES4_NS7_4lessISE_EENSC_INS7_4pairIKSE_S4_EEEEEERKNS7_6vectorIS4_NSC_IS4_EEEESS_SS_RKNS7_13unordered_mapISE_NS2_6TShapeENS7_4hashISE_EENS7_8equal_toISE_EENSC_INSH_ISI_SU_EEEEEERKNST_ISE_iSW_SY_NSC_INSH_ISI_iEEEEEES18_RKNSO_INS_9OpReqTypeENSC_IS19_EEEERKNS7_13unordered_setISE_SW_SY_NSC_ISE_EEEEPNSO_INS_7NDArrayENSC_IS1J_EEEES1M_S1M_PNST_ISE_S1J_SW_SY_NSC_INSH_ISI_S1J_EEEEEEPNS_8ExecutorERKNST_INS2_9NodeEntryES1J_NS2_13NodeEntryHashENS2_14NodeEntryEqualENSC_INSH_IKS1T_S1J_EEEEEE + 1030
[bt] (6) 6   libmxnet.so                         0x0000000104dc5606 _ZN5mxnet8Executor10SimpleBindEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEES3_NS6_4lessISD_EENSB_INS6_4pairIKSD_S3_EEEEEERKNS6_6vectorIS3_NSB_IS3_EEEESR_SR_RKNS6_13unordered_mapISD_NS1_6TShapeENS6_4hashISD_EENS6_8equal_toISD_EENSB_INSG_ISH_ST_EEEEEERKNSS_ISD_iSV_SX_NSB_INSG_ISH_iEEEEEES17_RKNSN_INS_9OpReqTypeENSB_IS18_EEEERKNS6_13unordered_setISD_SV_SX_NSB_ISD_EEEEPNSN_INS_7NDArrayENSB_IS1I_EEEES1L_S1L_PNSS_ISD_S1I_SV_SX_NSB_INSG_ISH_S1I_EEEEEEPS0_ + 230
[bt] (7) 7   libmxnet.so                         0x0000000104d66cd6 MXExecutorSimpleBind + 8038
[bt] (8) 8   _ctypes.cpython-36m-darwin.so       0x0000000102fbf247 ffi_call_unix64 + 79
[bt] (9) 9   ???                                 0x00007fff5de2e9b0 0x0 + 140734768540080
```

maybe you have different v. of mxnet? (my error is from 1.0.0post4).

anyway, pretty clear there is a compatibility issue with some of these models.

**Comment by Roshrini** [comment] 2018-02-19 22:09
The issue might be related to onnx-mxnet package. @spicyDev or @anirudhacharya can you take a look?

**Comment by anirudhacharya** [comment] 2018-02-19 22:10
I will take a look

**Comment by spidyDev** [comment] 2018-02-21 22:10
Looks like there are two issues here:
1. @jesterhazy - "Error in operator pad0: [11:36:00] src/operator/./pad-inl.h:211: Input shape vs padding spec mismatch."
     This is issue with onnx-mxnet import, I have a PR out for this https://github.com/onnx/onnx-mxnet/pull/27

2. @aaronmarkham  - I was able to replicate this issue from the VGG onnx model  from the pytorch doc. I think the problem is with the model. The "Reshape [10,-1]  layer seems to be incorrect, as this will always generate an error as per my  calculations. There is VGG-16 ONNX model available at https://github.com/onnx/models/tree/master/vgg16, which doesn't seem to have this layer.

**Comment by lupesko** [comment] 2018-03-15 06:25
Closing the issue.
@aaronmarkham feel free to re-open if closed in error.

**Closed by lupesko** 2018-03-15 06:25 UTC
Labels: bug
